import { reviews } from './reviews.js';

export const products = [
  {
    id: 1,
    name: "JBL E55BT KEY BLACK",
    price: 386,
    originalPrice: 451,
    brand: "JBL",
    category: "Wireless",
    color: "Black",
    rating: 3.2,
    image: "images/image1.webp",
    image2: "images/image1_2.webp",
    image3: "images/image1_3.webp",
    description: "The JBL E55BT KEY BLACK offers powerful bass and long battery life, making it perfect for those who want to enjoy their music on the go without worrying about constant recharging. Its comfortable over-ear design ensures that you can listen for hours without discomfort. With Bluetooth connectivity, you can easily pair it with your devices and enjoy a seamless wireless experience. The sound quality is exceptional, delivering deep bass and crisp highs, ideal for all music genres. Whether you're commuting, working out, or just relaxing at home, the JBL E55BT KEY BLACK is your go-to headphone.",
    onSale: true,
    microphone: true,
    unitsSold: 2452,
    favorited: 14652,
    uploadDate: "2022-10-05",
    reviewCount: reviews.find(review => review.id === 1)?.customers.length || 0,
  },
  {
    id: 2,
    name: "Sony JR 310BT",
    price: 532,
    originalPrice: 600,
    brand: "Sony",
    category: "Wireless",
    color: "Blue",
    rating: 4.3,
    image: "images/image2.webp",
    image2: "images/image2_2.webp",
    image3: "images/image2_3.webp",
    description: "Designed specifically for kids, the Sony JR 310BT features a comfortable and secure fit that ensures the headphones stay in place during any activity. The soft ear cushions provide additional comfort, making them suitable for long listening sessions. These headphones are built with durable materials that can withstand the rough and tumble of everyday use, ensuring they last for a long time. With a safe volume limit, parents can rest easy knowing their children's hearing is protected. The bright blue color adds a fun and stylish touch that kids will love.",
    onSale: true,
    microphone: false,
    unitsSold: 6685,
    favorited: 15966,
    uploadDate: "2022-12-22",
    reviewCount: reviews.find(review => review.id === 2)?.customers.length || 0,
  },
  {
    id: 3,
    name: "Logitech ZUNE 750BTNC",
    price: 1128,
    originalPrice: 1200,
    brand: "Logitech",
    category: "Over-ear headphone",
    color: "Red",
    rating: 4.6,
    image: "images/image3.webp",
    image2: "images/image3_2.webp",
    image3: "images/image3_3.webp",
    description: "The Logitech ZUNE 750BTNC is the ultimate choice for audiophiles who value sound clarity and immersive listening. With active noise cancellation, you can block out unwanted background noise and focus solely on your music or calls. Its long-lasting battery life allows you to enjoy up to 20 hours of uninterrupted playback, making it ideal for long trips or busy workdays. The over-ear design not only provides comfort but also enhances sound isolation. Whether you're at home, in the office, or on the go, the Logitech ZUNE 750BTNC offers an unparalleled audio experience.",
    onSale: true,
    microphone: true,
    unitsSold: 9944,
    favorited: 58376,
    uploadDate: "2023-05-02",
    reviewCount: reviews.find(review => review.id === 3)?.customers.length || 0,
  },
  {
    id: 4,
    name: "Sony Horizon",
    price: 380,
    originalPrice: 400,
    brand: "Sony",
    category: "Wireless",
    color: "Black",
    rating: 2.1,
    image: "images/image4.webp",
    image2: "images/image4_2.webp",
    image3: "images/image4_3.webp",
    description: "The Sony Horizon combines sleek aesthetics with impressive sound quality, making it a top choice for those who seek both style and performance. Its wireless connectivity provides freedom of movement without the hassle of tangled wires. The headphones deliver a balanced sound profile, with deep bass and clear mids and highs, perfect for a wide range of music genres. The lightweight design ensures that you can wear them comfortably for hours. Additionally, the Horizon is built with durable materials, ensuring longevity even with regular use.",
    onSale: true,
    microphone: true,
    unitsSold: 4211,
    favorited: 98976,
    uploadDate: "2023-08-12",
    reviewCount: reviews.find(review => review.id === 4)?.customers.length || 0,
  },
  {
    id: 5,
    name: "Beat Tune 220TWS",
    price: 620,
    originalPrice: 650,
    brand: "Beat",
    category: "In-ear headphone",
    color: "Pink",
    rating: 2.9,
    image: "images/image5.webp",
    image2: "images/image5_2.webp",
    image3: "images/image5_3.webp",
    description: "The Beat Tune 220TWS in-ear headphones offer a seamless wireless experience with a stylish and compact design. These earbuds are perfect for those who are always on the move, providing a secure fit that stays in place during any activity. With Bluetooth connectivity, you can easily pair them with your smartphone or other devices. The sound quality is crisp and clear, delivering a balanced audio experience that enhances your favorite tracks. The trendy pink finish adds a touch of personality to your look, making these earbuds a fashion-forward choice.",
    onSale: true,
    microphone: false,
    unitsSold: 6939,
    favorited: 89158,
    uploadDate: "2023-04-06",
    reviewCount: reviews.find(review => review.id === 5)?.customers.length || 0,
  },
  {
    id: 6,
    name: "Samsung UA Project Rock",
    price: 1500,
    originalPrice: 1600,
    brand: "Samsung",
    category: "Sport headphone",
    color: "Black",
    rating: 4.8,
    image: "images/image6.webp",
    image2: "images/image6_2.webp",
    image3: "images/image6_3.webp",
    description: "The UA Project Rock by Samsung is engineered to meet the needs of the most demanding athletes. With a focus on durability and performance, these headphones are perfect for intense workout sessions. The secure and comfortable fit ensures that they stay in place no matter how rigorous your activity. Crafted with premium materials, the UA Project Rock is built to last, making it a reliable companion for your fitness journey. Additionally, the sound quality is exceptional, delivering clear and powerful audio that keeps you motivated during your workouts. These headphones are designed to endure the toughest conditions, so you can push your limits without any distractions.",
    onSale: true,
    microphone: true,
    unitsSold: 2829,
    favorited: 31032,
    uploadDate: "2024-07-21",
    reviewCount: reviews.find(review => review.id === 6)?.customers.length || 0,
  },
  {
    id: 7,
    name: "Logitech Endurance RUN",
    price: 380,
    originalPrice: 400,
    brand: "Logitech",
    category: "Sport headphone",
    color: "Yellow",
    rating: 4.1,
    image: "images/image7.webp",
    image2: "images/image7_2.webp",
    image3: "images/image7_3.webp",
    description: "The Logitech Endurance RUN is designed for those who take their workouts seriously. These sport headphones feature a secure fit and a sweatproof design, making them ideal for intense physical activities. The ergonomic design ensures that they stay in place, even during the most vigorous exercises. With high-quality sound and durability, these headphones provide a reliable and enjoyable listening experience. The bright yellow color adds a bold and energetic look, making them not only functional but also stylish. Whether you're running, cycling, or hitting the gym, the Endurance RUN will keep up with you every step of the way.",
    onSale: true,
    microphone: false,
    unitsSold: 2426,
    favorited: 27972,
    uploadDate: "2023-01-13",
    reviewCount: reviews.find(review => review.id === 7)?.customers.length || 0,
  },
  {
    id: 8,
    name: "Logitech LIVE 650BTNC",
    price: 1960,
    originalPrice: 2000,
    brand: "Logitech",
    category: "Over-ear headphone",
    color: "Blue",
    rating: 4.9,
    image: "images/image1.webp",
    image2: "images/image1_2.webp",
    image3: "images/image1_3.webp",
    description: "The Logitech LIVE 650BTNC is designed for those who demand the best in sound quality and noise cancellation. These over-ear headphones offer premium sound, allowing you to enjoy your music without any interruptions. The active noise cancellation feature blocks out unwanted background noise, making them perfect for immersive listening experiences. With long battery life, you can enjoy hours of uninterrupted playback. The stylish blue design adds a modern touch, making these headphones not only functional but also fashionable. Whether you're commuting, working, or just relaxing, the LIVE 650BTNC provides an exceptional audio experience.",
    onSale: true,
    microphone: true,
    unitsSold: 2778,
    favorited: 71807,
    uploadDate: "2024-02-03",
    reviewCount: reviews.find(review => review.id === 8)?.customers.length || 0,
  },
  {
    id: 9,
    name: "Sony Reflect Flow",
    price: 760,
    originalPrice: 800,
    brand: "Sony",
    category: "Wireless",
    color: "Black",
    rating: 4.0,
    image: "images/image2.webp",
    image2: "images/image2_2.webp",
    image3: "images/image2_3.webp",
    description: "The Sony Reflect Flow is designed for those who lead an active lifestyle. These wireless headphones offer a secure fit and sweatproof features, making them ideal for workouts and outdoor activities. The durable design ensures that they can withstand the rigors of daily use, while the high-quality sound provides a satisfying listening experience. The sleek black finish adds a touch of elegance, making them a great choice for both fitness enthusiasts and casual listeners. Whether you're hitting the gym or just enjoying your favorite tunes, the Reflect Flow will keep you connected and motivated.",
    onSale: true,
    microphone: false,
    unitsSold: 3107,
    favorited: 34836,
    uploadDate: "2024-05-30",
    reviewCount: reviews.find(review => review.id === 9)?.customers.length || 0,
  },
  {
    id: 10,
    name: "Beat Free X",
    price: 950,
    originalPrice: 1000,
    brand: "Beat",
    category: "Wireless",
    color: "White",
    rating: 1.6,
    image: "images/image3.webp",
    image2: "images/image3_2.webp",
    image3: "images/image3_3.webp",
    description: "The Beat Free X offers the ultimate in wireless freedom, with excellent sound quality and a sleek white design. These true wireless earbuds are designed for those who want to enjoy their music without the hassle of wires. The compact design makes them easy to carry, while the secure fit ensures they stay in place during any activity. With long battery life, you can enjoy hours of uninterrupted listening. The sound quality is exceptional, delivering clear highs and deep bass. Whether you're commuting, working out, or just relaxing, the Beat Free X provides a hassle-free and enjoyable listening experience.",
    onSale: false,
    microphone: true,
    unitsSold: 7386,
    favorited: 78349,
    uploadDate: "2023-06-22",
    reviewCount: reviews.find(review => review.id === 10)?.customers.length || 0,
  },
  {
    id: 11,
    name: "Logitech E55BT KEY BLACK",
    price: 380,
    originalPrice: 400,
    brand: "Logitech",
    category: "In-ear headphone",
    color: "Black",
    rating: 2.5,
    image: "images/image4.webp",
    image2: "images/image4_2.webp",
    image3: "images/image4_3.webp",
    description: "Enjoy powerful sound and long battery life with the Logitech E55BT KEY BLACK. These in-ear headphones offer an immersive listening experience with wireless connectivity that allows for seamless pairing with your devices. The ergonomic design ensures a comfortable fit, making them perfect for extended use. Whether you're commuting, working out, or simply relaxing, the E55BT KEY BLACK delivers rich audio with deep bass and clear highs. The durable build and stylish black finish make these headphones not only functional but also a fashionable accessory. With long-lasting battery life, you can enjoy your music all day without interruption.",
    onSale: true,
    microphone: true,
    unitsSold: 9861,
    favorited: 77124,
    uploadDate: "2022-11-22",
    reviewCount: reviews.find(review => review.id === 11)?.customers.length || 0,
  },
  {
    id: 12,
    name: "Samsung JR 310BT",
    price: 490,
    originalPrice: 500,
    brand: "Samsung",
    category: "Wireless",
    color: "Blue",
    rating: 4.0,
    image: "images/image5.webp",
    image2: "images/image5_2.webp",
    image3: "images/image5_3.webp",
    description: "The Samsung JR 310BT is designed with kids in mind, offering a comfortable fit and a durable build that can withstand daily use. These wireless headphones are perfect for young listeners, with a safe volume limit to protect their hearing. The bright blue color and fun design make them a hit with children, while the sturdy construction ensures they last through all kinds of adventures. Parents will appreciate the ease of wireless connectivity, allowing kids to enjoy their favorite music, videos, and games without any tangled wires. These headphones provide a safe and enjoyable listening experience for kids.",
    onSale: true,
    microphone: false,
    unitsSold: 2417,
    favorited: 48902,
    uploadDate: "2023-05-02",
    reviewCount: reviews.find(review => review.id === 12)?.customers.length || 0,
  },
  {
    id: 13,
    name: "JBL TUNE 750BTNC",
    price: 1280,
    originalPrice: 1300,
    brand: "JBL",
    category: "Over-ear headphone",
    color: "Red",
    rating: 3.7,
    image: "images/image6.webp",
    image2: "images/image6_2.webp",
    image3: "images/image6_3.webp",
    description: "Experience premium sound quality with the JBL TUNE 750BTNC, featuring active noise cancellation that lets you enjoy your music without any distractions. These over-ear headphones are designed for those who demand the best in audio performance, with deep bass and crystal-clear highs that bring your music to life. The long-lasting battery ensures that you can listen for hours on end without needing to recharge. The bold red color adds a touch of style, making these headphones a great accessory for any music lover. Ideal for travel, work, or relaxation, the TUNE 750BTNC offers an unparalleled listening experience.",
    onSale: true,
    microphone: true,
    unitsSold: 4330,
    favorited: 20023,
    uploadDate: "2022-11-23",
    reviewCount: reviews.find(review => review.id === 13)?.customers.length || 0,
  },
  {
    id: 14,
    name: "Sony Five Horizon",
    price: 460,
    originalPrice: 500,
    brand: "Sony",
    category: "Wireless",
    color: "Black",
    rating: 4.2,
    image: "images/image7.webp",
    image2: "images/image7_2.webp",
    image3: "images/image7_3.webp",
    description: "The Sony Five Horizon combines sleek design with high functionality, offering a premium wireless audio experience. These headphones are perfect for those who value both style and performance, with a sleek black finish that complements any look. The high-quality sound ensures an immersive listening experience, with rich bass and clear treble. The lightweight design and comfortable fit make them ideal for long listening sessions, whether you're at home or on the go. The Sony Horizon is built to last, with durable materials that can withstand daily use, making it a reliable choice for any music lover.",
    onSale: true,
    microphone: true,
    unitsSold: 7361,
    favorited: 23556,
    uploadDate: "2023-11-07",
    reviewCount: reviews.find(review => review.id === 14)?.customers.length || 0,
  },
  {
    id: 15,
    name: "Beat Tune 220TWS",
    price: 720,
    originalPrice: 750,
    brand: "Beat",
    category: "In-ear headphone",
    color: "Pink",
    rating: 3.8,
    image: "images/image1.webp",
    image2: "images/image1_2.webp",
    image3: "images/image1_3.webp",
    description: "The Beat Tune 220TWS offers a chic and stylish listening experience with true wireless capabilities. These in-ear headphones feature a trendy pink design, making them a fashionable accessory as well as a functional one. The comfortable fit ensures they stay in place, even during active use. With clear sound quality and easy Bluetooth connectivity, the Tune 220TWS is perfect for those who want to enjoy their music without the hassle of wires. Whether you're commuting, exercising, or just relaxing, these earbuds provide a seamless and enjoyable audio experience.",
    onSale: true,
    microphone: false,
    unitsSold: 9650,
    favorited: 36212,
    uploadDate: "2022-09-08",
    reviewCount: reviews.find(review => review.id === 15)?.customers.length || 0,
  },
  {
    id: 16,
    name: "Logitech Project Rock",
    price: 1550,
    originalPrice: 1600,
    brand: "Logitech",
    category: "Sport headphone",
    color: "Black",
    rating: 1.8,
    image: "images/image2.webp",
    image2: "images/image2_2.webp",
    image3: "images/image2_3.webp",
    description: "Designed specifically for athletes, the Logitech Project Rock offers outstanding sound quality and exceptional durability, making it the perfect companion for intense workouts. Built with premium materials, these sport headphones are designed to withstand the toughest conditions, ensuring they stay in place during your most rigorous activities. The powerful bass and clear highs provide an immersive audio experience, helping to keep you motivated throughout your exercise routine. Whether you're lifting weights, running, or doing high-intensity training, the Logitech Project Rock delivers reliable performance and comfort every time.",
    onSale: false,
    microphone: true,
    unitsSold: 7447,
    favorited: 72192,
    uploadDate: "2023-07-28",
    reviewCount: reviews.find(review => review.id === 16)?.customers.length || 0,
  },
  {
    id: 17,
    name: "JBL Endurance RUN",
    price: 380,
    originalPrice: 400,
    brand: "JBL",
    category: "Sport headphone",
    color: "Yellow",
    rating: 3.2,
    image: "images/image3.webp",
    image2: "images/image3_2.webp",
    image3: "images/image3_3.webp",
    description: "The JBL Endurance RUN is designed for those who need reliable performance during their most rigorous workouts. With a secure fit and sweatproof design, these sport headphones ensure you stay comfortable and focused on your exercise. The vibrant yellow color adds a touch of energy to your gear, while the durable construction means they can handle the toughest conditions. The sound quality is clear and robust, providing the motivation you need to push through your limits. Perfect for running, gym sessions, or any high-energy activity, the Endurance RUN is a must-have for active individuals.",
    onSale: true,
    microphone: false,
    unitsSold: 4415,
    favorited: 40155,
    uploadDate: "2023-09-02",
    reviewCount: reviews.find(review => review.id === 17)?.customers.length || 0,
  },
  {
    id: 18,
    name: "Sony DIVE 650BTNC",
    price: 1900,
    originalPrice: 2000,
    brand: "Sony",
    category: "Over-ear headphone",
    color: "Blue",
    rating: 4.8,
    image: "images/image4.webp",
    image2: "images/image4_2.webp",
    image3: "images/image4_3.webp",
    description: "The Sony DIVE 650BTNC offers an immersive listening experience with high-quality sound and effective noise cancellation. These over-ear headphones are designed to block out distractions, allowing you to enjoy your music in peace. The sleek design and comfortable fit make them ideal for long listening sessions, whether you're traveling, working, or relaxing. With a long-lasting battery, you can enjoy hours of uninterrupted playback. The stylish blue color adds a modern touch, making these headphones not only functional but also a fashion statement. The DIVE 650BTNC is the perfect blend of performance and style.",
    onSale: true,
    microphone: true,
    unitsSold: 2322,
    favorited: 30447,
    uploadDate: "2022-09-29",
    reviewCount: reviews.find(review => review.id === 18)?.customers.length || 0,
  },
  {
    id: 19,
    name: "Beat Reflect Flow",
    price: 760,
    originalPrice: 800,
    brand: "Beat",
    category: "Wireless",
    color: "Black",
    rating: 4.1,
    image: "images/image5.webp",
    image2: "images/image5_2.webp",
    image3: "images/image5_3.webp",
    description: "The Beat Reflect Flow is designed for those who need a reliable and secure fit during their workouts. These wireless headphones offer durability and a sweatproof design, ensuring they stay in place even during the most intense activities. The sound quality is robust, providing clear audio that keeps you motivated. The sleek black design adds a touch of sophistication to your workout gear. Whether you're at the gym, running outdoors, or doing any physical activity, the Reflect Flow delivers the performance you need to stay focused and energized.",
    onSale: true,
    microphone: false,
    unitsSold: 5466,
    favorited: 12372,
    uploadDate: "2023-11-19",
    reviewCount: reviews.find(review => review.id === 19)?.customers.length || 0,
  },
  {
    id: 20,
    name: "Logitech Free X",
    price: 950,
    originalPrice: 1000,
    brand: "Logitech",
    category: "In-ear headphone",
    color: "White",
    rating: 2.7,
    image: "images/image6.webp",
    image2: "images/image6_2.webp",
    image3: "images/image6_3.webp",
    description: "The Logitech Free X offers true wireless convenience with excellent sound quality, making it the perfect choice for those who value both performance and style. These in-ear headphones provide a hassle-free listening experience, allowing you to enjoy your favorite music without any tangled wires. The stylish white design adds a modern touch, making them a fashionable accessory as well as a functional one. With a secure fit and long battery life, the Free X is ideal for commuting, exercising, or any daily activity. Experience clear and powerful sound with the convenience of wireless freedom.",
    onSale: true,
    microphone: true,
    unitsSold: 8173,
    favorited: 93868,
    uploadDate: "2024-04-21",
    reviewCount: reviews.find(review => review.id === 20)?.customers.length || 0,
  },
  {
    id: 21,
    name: "Samsung E55BT KEY BLACK",
    price: 390,
    originalPrice: 420,
    brand: "Samsung",
    category: "Wireless",
    color: "Black",
    rating: 4.4,
    image: "images/image7.webp",
    image2: "images/image7_2.webp",
    image3: "images/image7_3.webp",
    description: "The Samsung E55BT KEY BLACK delivers a powerful audio experience with a blend of style and functionality. These wireless headphones are designed for those who value both sound quality and comfort. With a long battery life, you can enjoy your favorite music, podcasts, or audiobooks for hours without interruption. The ergonomic design ensures a secure and comfortable fit, making them ideal for daily use, whether you're at the gym, commuting, or just relaxing at home. The sleek black finish adds a touch of elegance, making these headphones a versatile accessory for any occasion.",
    onSale: true,
    microphone: true,
    unitsSold: 4929,
    favorited: 65770,
    uploadDate: "2024-02-28",
    reviewCount: reviews.find(review => review.id === 21)?.customers.length || 0,
  },
  {
    id: 22,
    name: "JBL JR 310BT",
    price: 510,
    originalPrice: 540,
    brand: "JBL",
    category: "Wireless",
    color: "Blue",
    rating: 4.1,
    image: "images/image2.webp",
    image2: "images/image2_2.webp",
    image3: "images/image2_3.webp",
    description: "The JBL JR 310BT is specifically designed for kids, offering a comfortable and durable listening experience. These wireless headphones feature a safe volume limit to protect young ears while delivering vibrant sound quality. The sturdy construction ensures they can withstand the rough and tumble of everyday use, making them a reliable choice for active children. The bright blue design is both fun and stylish, appealing to kids and parents alike. With easy wireless connectivity, kids can enjoy their favorite music and media without the hassle of tangled wires, making the JR 310BT a perfect companion for on-the-go entertainment.",
    onSale: true,
    microphone: false,
    unitsSold: 6108,
    favorited: 73335,
    uploadDate: "2023-09-11",
    reviewCount: reviews.find(review => review.id === 22)?.customers.length || 0,
  },
  {
    id: 23,
    name: "Beat TUNE 750BTNC",
    price: 1300,
    originalPrice: 1350,
    brand: "Beat",
    category: "In-ear headphone",
    color: "Red",
    rating: 4.8,
    image: "images/image3.webp",
    image2: "images/image3_2.webp",
    image3: "images/image3_3.webp",
    description: "The Beat TUNE 750BTNC offers a premium audio experience with active noise cancellation, allowing you to enjoy uninterrupted listening in any environment. These in-ear headphones are perfect for those who demand high-quality sound and comfort. The stylish red design adds a bold touch, making them not only functional but also a fashion statement. With long battery life, you can immerse yourself in your music for hours without needing to recharge. Whether you're traveling, working, or just relaxing, the TUNE 750BTNC provides the clarity and depth of sound that audiophiles will appreciate.",
    onSale: true,
    microphone: true,
    unitsSold: 4298,
    favorited: 47856,
    uploadDate: "2023-10-15",
    reviewCount: reviews.find(review => review.id === 23)?.customers.length || 0,
  },
  {
    id: 24,
    name: "Beat Horizon",
    price: 470,
    originalPrice: 490,
    brand: "Beat",
    category: "Wireless",
    color: "Black",
    rating: 4.3,
    image: "images/image4.webp",
    image2: "images/image4_2.webp",
    image3: "images/image4_3.webp",
    description: "The Beat Horizon combines elegance and performance in a sleek wireless headphone. These headphones offer excellent sound quality, making them ideal for those who appreciate both style and functionality. The ergonomic design ensures a comfortable fit for extended listening sessions, while the durable build provides reliability for everyday use. Whether you're enjoying music at home, on your commute, or during workouts, the Horizon delivers clear and powerful audio. The stylish black finish adds a sophisticated touch, making these headphones a versatile choice for any occasion.",
    onSale: false,
    microphone: true,
    unitsSold: 9669,
    favorited: 99326,
    uploadDate: "2023-04-12",
    reviewCount: reviews.find(review => review.id === 24)?.customers.length || 0,
  },
  {
    id: 25,
    name: "Beat Tune 220TWS",
    price: 730,
    originalPrice: 770,
    brand: "Beat",
    category: "In-ear headphone",
    color: "Pink",
    rating: 4.0,
    image: "images/image5.webp",
    image2: "images/image5_2.webp",
    image3: "images/image5_3.webp",
    description: "The Beat Tune 220TWS offers true wireless convenience with a stylish pink design. These in-ear headphones deliver high-quality sound with clear highs and deep bass, making them perfect for music lovers on the go. The compact and lightweight design ensures a comfortable fit, while the wireless connectivity allows for hassle-free listening without tangled wires. The trendy pink finish adds a touch of flair, making these earbuds a fashionable accessory as well as a functional one. Whether you're commuting, working out, or just relaxing, the Tune 220TWS provides a seamless and enjoyable audio experience.",
    onSale: true,
    microphone: false,
    unitsSold: 2319,
    favorited: 44864,
    uploadDate: "2023-12-07",
    reviewCount: reviews.find(review => review.id === 25)?.customers.length || 0,
  },
  {
    id: 26,
    name: "Beat Project Rock",
    price: 1600,
    originalPrice: 1650,
    brand: "Beat",
    category: "Sport headphone",
    color: "Black",
    rating: 4.8,
    image: "images/image6.webp",
    image2: "images/image6_2.webp",
    image3: "images/image6_3.webp",
    description: "Built for athletes, the Beat Project Rock offers exceptional sound quality and rugged durability, making it the ideal choice for intense workouts. These sport headphones are designed to withstand the toughest conditions, with premium materials that ensure longevity and performance. The secure and comfortable fit means you can move freely without worrying about your headphones slipping or falling out. Whether you're lifting weights, running, or engaging in high-intensity training, the Project Rock delivers the powerful sound and durability needed to keep you motivated and focused throughout your workout.",
    onSale: true,
    microphone: true,
    unitsSold: 7923,
    favorited: 88663,
    uploadDate: "2023-02-13",
    reviewCount: reviews.find(review => review.id === 26)?.customers.length || 0,
  },
  {
    id: 27,
    name: "Logitech Endurance RUN",
    price: 400,
    originalPrice: 430,
    brand: "Logitech",
    category: "Sport headphone",
    color: "Yellow",
    rating: 4.4,
    image: "images/image7.webp",
    image2: "images/image7_2.webp",
    image3: "images/image7_3.webp",
    description: "The Logitech Endurance RUN is crafted for athletes who demand reliable performance and comfort during their workouts. Featuring a secure fit and sweatproof design, these sport headphones stay in place even during the most vigorous activities. The vibrant yellow color adds a dynamic touch, while the durable construction ensures they can handle the wear and tear of daily use. The sound quality is clear and robust, providing the motivation you need to push through your limits. Perfect for running, gym sessions, or any intense exercise, the Endurance RUN is a must-have for active individuals.",
    onSale: true,
    microphone: false,
    unitsSold: 4044,
    favorited: 34400,
    uploadDate: "2023-02-25",
    reviewCount: reviews.find(review => review.id === 27)?.customers.length || 0,
  },
  {
    id: 28,
    name: "JBL LIVE 650BTNC",
    price: 2000,
    originalPrice: 2200,
    brand: "JBL",
    category: "Over-ear headphone",
    color: "Blue",
    rating: 4.9,
    image: "images/image1.webp",
    image2: "images/image1_2.webp",
    image3: "images/image1_3.webp",
    description: "The JBL LIVE 650BTNC offers superior sound quality with active noise cancellation, making it perfect for those who demand a premium audio experience. These over-ear headphones provide an immersive listening experience, blocking out external noise so you can focus on your music. The long battery life ensures you can enjoy your favorite tracks for hours on end, while the comfortable design makes them ideal for extended use. The sleek blue finish adds a modern touch, making these headphones a stylish and functional accessory for any occasion.",
    onSale: true,
    microphone: true,
    unitsSold: 6463,
    favorited: 52397,
    uploadDate: "2023-11-05",
    reviewCount: reviews.find(review => review.id === 28)?.customers.length || 0,
  },
  {
    id: 29,
    name: "Beat Reflect Flow",
    price: 790,
    originalPrice: 850,
    brand: "Beat",
    category: "Wireless",
    color: "Black",
    rating: 4.3,
    image: "images/image2.webp",
    image2: "images/image2_2.webp",
    image3: "images/image2_3.webp",
    description: "The Beat Reflect Flow is designed for those who need a reliable and secure fit during their workouts. These wireless headphones offer durability and a sweatproof design, ensuring they stay in place even during the most intense activities. The sound quality is robust, providing clear audio that keeps you motivated. The sleek black design adds a touch of sophistication to your workout gear. Whether you're at the gym, running outdoors, or doing any physical activity, the Reflect Flow delivers the performance you need to stay focused and energized.",
    onSale: true,
    microphone: false,
    unitsSold: 6353,
    favorited: 78493,
    uploadDate: "2024-03-27",
    reviewCount: reviews.find(review => review.id === 29)?.customers.length || 0,
  },
  {
    id: 30,
    name: "Logitech Free X",
    price: 1000,
    originalPrice: 1050,
    brand: "Logitech",
    category: "Wireless",
    color: "White",
    rating: 4.7,
    image: "images/image3.webp",
    image2: "images/image3_2.webp",
    image3: "images/image3_3.webp",
    description: "The Logitech Free X delivers true wireless freedom with a stylish white design and high-quality sound. These in-ear headphones offer a seamless listening experience, with Bluetooth connectivity that ensures a strong and stable connection to your devices. The lightweight and comfortable fit make them ideal for all-day wear, whether you're commuting, working out, or just relaxing. The long battery life allows you to enjoy hours of uninterrupted music, podcasts, or calls. With a sleek and modern look, the Free X is both a fashionable and functional choice for anyone looking for wireless convenience.",
    onSale: true,
    microphone: true,
    unitsSold: 5224,
    favorited: 86887,
    uploadDate: "2023-04-09",
    reviewCount: reviews.find(review => review.id === 30)?.customers.length || 0,
  },
  {
    id: 31,
    name: "Beat E55BT KEY BLACK",
    price: 400,
    originalPrice: 440,
    brand: "Beat",
    category: "In-ear headphone",
    color: "Black",
    rating: 4.5,
    image: "images/image4.webp",
    image2: "images/image4_2.webp",
    image3: "images/image4_3.webp",
    description: "The Beat E55BT KEY BLACK offers powerful sound and a comfortable fit, making it an excellent choice for those who value both audio quality and convenience. These in-ear headphones feature long battery life, allowing you to enjoy your music without interruptions. The wireless design ensures freedom of movement, whether you're at the gym, commuting, or just relaxing at home. The stylish black finish adds a sleek touch, making these headphones not only functional but also a fashionable accessory. With its impressive sound performance, the E55BT KEY BLACK offers an immersive listening experience that you can enjoy all day.",
    onSale: true,
    microphone: true,
    unitsSold: 3941,
    favorited: 69200,
    uploadDate: "2024-03-31",
    reviewCount: reviews.find(review => review.id === 31)?.customers.length || 0,
  },
  {
    id: 32,
    name: "Beat JR 310BT",
    price: 530,
    originalPrice: 550,
    brand: "Beat",
    category: "In-ear headphone",
    color: "Blue",
    rating: 4.2,
    image: "images/image5.webp",
    image2: "images/image5_2.webp",
    image3: "images/image5_3.webp",
    description: "The Beat JR 310BT is specially designed for kids, offering a durable and comfortable fit for safe wireless listening. These in-ear headphones provide vibrant sound quality, making them perfect for young music lovers. The sturdy construction ensures that they can withstand the daily wear and tear of active children. The bright blue design is both fun and stylish, appealing to both kids and parents. With easy wireless connectivity and a safe volume limit, the JR 310BT allows children to enjoy their favorite music and media with peace of mind, making it an ideal choice for families.",
    onSale: false,
    microphone: false,
    unitsSold: 9108,
    favorited: 63481,
    uploadDate: "2022-12-31",
    reviewCount: reviews.find(review => review.id === 32)?.customers.length || 0,
  },
  {
    id: 33,
    name: "JBL TUNE 750BTNC",
    price: 1250,
    originalPrice: 1400,
    brand: "JBL",
    category: "Over-ear headphone",
    color: "Red",
    rating: 4.6,
    image: "images/image6.webp",
    image2: "images/image6_2.webp",
    image3: "images/image6_3.webp",
    description: "The JBL TUNE 750BTNC offers exceptional sound quality with active noise cancellation, making it perfect for those who seek an immersive audio experience. These over-ear headphones provide long-lasting comfort, allowing you to enjoy your music for hours without discomfort. The sleek red design adds a bold and stylish touch, making these headphones a standout accessory. With a durable build and easy wireless connectivity, the TUNE 750BTNC is ideal for travel, work, or leisure. Whether you're commuting or relaxing at home, these headphones deliver clear, powerful sound that enhances your listening experience.",
    onSale: true,
    microphone: true,
    unitsSold: 9917,
    favorited: 95302,
    uploadDate: "2023-01-04",
    reviewCount: reviews.find(review => review.id === 33)?.customers.length || 0,
  },
  {
    id: 34,
    name: "Samsung Horizon",
    price: 450,
    originalPrice: 500,
    brand: "Samsung",
    category: "In-ear headphone",
    color: "Black",
    rating: 4.4,
    image: "images/image7.webp",
    image2: "images/image7_2.webp",
    image3: "images/image7_3.webp",
    description: "The Samsung Horizon offers a perfect combination of elegance and excellent sound quality. These in-ear headphones are ideal for those who value both style and functionality in their wireless audio experience. With a sleek design and a comfortable fit, the Horizon ensures that you can listen to your favorite music for extended periods without discomfort. The durable build provides reliability, making these headphones a great choice for everyday use. Whether you're working out, commuting, or just relaxing, the Horizon delivers clear and balanced sound that enhances your listening experience.",
    onSale: true,
    microphone: true,
    unitsSold: 7534,
    favorited: 61294,
    uploadDate: "2023-07-03",
    reviewCount: reviews.find(review => review.id === 34)?.customers.length || 0,
  },
  {
    id: 35,
    name: "Beat Tune 220TWS",
    price: 750,
    originalPrice: 800,
    brand: "Beat",
    category: "In-ear headphone",
    color: "Pink",
    rating: 4.1,
    image: "images/image1.webp",
    image2: "images/image1_2.webp",
    image3: "images/image1_3.webp",
    description: "The Beat Tune 220TWS provides a chic pink design with high-quality sound, making it perfect for those who value both aesthetics and performance. These true wireless earbuds offer a comfortable fit and clear sound, ensuring that you can enjoy your music with ease. The compact and lightweight design makes them easy to carry and wear all day long. With reliable wireless connectivity, you can enjoy your favorite tracks without the hassle of tangled wires. The Tune 220TWS is an excellent choice for anyone looking for stylish and functional earbuds that deliver a seamless audio experience.",
    onSale: true,
    microphone: false,
    unitsSold: 5463,
    favorited: 29288,
    uploadDate: "2023-01-08",
    reviewCount: reviews.find(review => review.id === 35)?.customers.length || 0,
  },
  {
    id: 36,
    name: "Samsung Project Rock",
    price: 1650,
    originalPrice: 1700,
    brand: "Samsung",
    category: "Sport headphone",
    color: "Black",
    rating: 4.8,
    image: "images/image2.webp",
    image2: "images/image2_2.webp",
    image3: "images/image2_3.webp",
    description: "Built for athletes, the UA Project Rock offers robust sound and durability. Ideal for intense workouts with a comfortable and secure fit.",
    onSale: true,
    microphone: true,
    unitsSold: 9395,
    favorited: 46749,
    uploadDate: "2023-01-30",
    reviewCount: reviews.find(review => review.id === 36)?.customers.length || 0,
  },
  {
    id: 37,
    name: "Beat Endurance RUN",
    price: 420,
    originalPrice: 450,
    brand: "Beat",
    category: "Sport headphone",
    color: "Yellow",
    rating: 4.5,
    image: "images/image3.webp",
    image2: "images/image3_2.webp",
    image3: "images/image3_3.webp",
    description: "The JBL Endurance RUN is designed for athletes, featuring a secure fit and sweatproof features. Enjoy reliable performance and clear sound during your workouts.",
    onSale: true,
    microphone: false,
    unitsSold: 8670,
    favorited: 43845,
    uploadDate: "2023-11-11",
    reviewCount: reviews.find(review => review.id === 37)?.customers.length || 0,
  },
  {
    id: 38,
    name: "Logitech LIVE 650BTNC",
    price: 2050,
    originalPrice: 2250,
    brand: "Logitech",
    category: "Over-ear headphone",
    color: "Blue",
    rating: 4.9,
    image: "images/image4.webp",
    image2: "images/image4_2.webp",
    image3: "images/image4_3.webp",
    description: "The JBL LIVE 650BTNC offers superior sound with active noise cancellation. Perfect for extended comfort and a premium audio experience.",
    onSale: true,
    microphone: true,
    unitsSold: 2483,
    favorited: 12523,
    uploadDate: "2023-05-11",
    reviewCount: reviews.find(review => review.id === 38)?.customers.length || 0,
  },
  {
    id: 39,
    name: "Sony Reflect Flow",
    price: 820,
    originalPrice: 880,
    brand: "Sony",
    category: "In-ear headphone",
    color: "Black",
    rating: 4.4,
    image: "images/image5.webp",
    image2: "images/image5_2.webp",
    image3: "images/image5_3.webp",
    descriptin: "The JBL Reflect Flow is designed for active users with a secure fit and sweatproof durability. Enjoy high-quality sound and a rugged design.",
    onSale: true,
    microphone: false,
    unitsSold: 9238,
    favorited: 97334,
    uploadDate: "2023-03-29",
    reviewCount: reviews.find(review => review.id === 39)?.customers.length || 0,
  },
  {
    id: 40,
    name: "Sony Free X",
    price: 1050,
    originalPrice: 1100,
    brand: "Sony",
    category: "In-ear headphone",
    color: "White",
    rating: 4.8,
    image: "images/image6.webp",
    image2: "images/image6_2.webp",
    image3: "images/image6_3.webp",
    description: "The JBL Free X offers true wireless freedom with a sleek white design and high-quality sound. Enjoy an effortless and enjoyable listening experience.",
    onSale: true,
    microphone: true,
    unitsSold: 4508,
    favorited: 65245,
    uploadDate: "2023-08-16",
    reviewCount: reviews.find(review => review.id === 40)?.customers.length || 0,
  }
];
